name: Convert LaTeX to PDF

on:
  workflow_dispatch
jobs:
  makepdf:
    name: Convert LaTeX to PDF
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install LaTeX Things
      run: |
        sudo apt-get update && sudo apt-get install texlive-humanities latexmk -y
    - name: Convert Files
      run: |
        cd tex/
        ./makepdf.sh