name: Convert LaTeX to PDF

on:
  workflow_dispatch
jobs:
  makepdf:
    name: Convert LaTeX to PDF
    runs-on: ubuntu-latest
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v2
    - name: Install LaTeX Things
      run: |
        apt-get update && apt-get install texlive texlive-lang-german texlive-latex-extra latexmk -y --no-install-recommend
    - name: Convert Files
      run: |
        cd tex/
        ./makepdf.sh